[distribution.ansible]
end-of-life = [
  'stable-2.15',
  'stable-2.14',
  'stable-2.13',
]
supported = [
  'devel',
  'stable-2.18',
  'stable-2.17',
  'stable-2.16',
]

[distribution.ansible-core]
end-of-life = [
  'stable-2.15',
  'stable-2.14',
  'stable-2.13',
]
supported = [
  'devel',
  'stable-2.18',
  'stable-2.17',
  'stable-2.16',
]
